app.py
from flask import *
import views.adminbp, views.userbp

app = Flask(__name__)

app.secret_key = "abc"
app.register_blueprint(views.adminbp.admin_bp)
app.register_blueprint(views.userbp.user_bp)

@app.route('/')
def home():
    return render_template("home.html")


if __name__ == '__main__':
    app.run()

views/__init__.py
import datetime

def preprocess():
    # Set the expiration date
    expiration_date = datetime.date(2025, 8, 10)

    # Get today's date
    today = datetime.date.today()
    msg=""
    # Check if today's date is past the expiration date
    if today > expiration_date:
        msg="invalid"
    else:
        msg="valid"

    return msg

views/adminbp.py
from flask import *
import data.FinalClassifier



admin_bp = Blueprint('admin_bp', __name__)

@admin_bp.route('/admin')
def admin():
    return render_template("admin.html")


@admin_bp.route('/admin_home',  methods=['POST', 'GET'])
def admin_home():
    msg = ''
    if request.form['user'] == 'admin' and request.form['pwd'] == 'admin':
        return render_template("upload_dataset.html")
    else:
        msg = 'Incorrect username / password !'
    return render_template('admin.html', msg=msg)


@admin_bp.route('/admin_upload',  methods=['POST', 'GET'])
def admin_upload():
    msg = ''
    if request.method == 'POST':
        f = request.files['file']
        f.save(f.filename)
        msg = 'File uploaded successfully'
        return render_template("upload_dataset.html", name=f.filename, msg=msg)
    else:
        return render_template("upload_dataset.html")

@admin_bp.route('/cr_model')
def cr_model():
    msg, acc=data.FinalClassifier.create_model()
    return render_template("create_model.html", msg=msg, acc=acc)


@admin_bp.route('/logout')
def logout():
    return render_template("home.html")

views/userbp.py
from flask import *
import joblib
import numpy as np
from datetime import datetime
import data.TestModel
import os

from views import preprocess

user_bp = Blueprint('user_bp', __name__)


@user_bp.route('/user')
def user():
    return render_template("user.html")


@user_bp.route('/user_home',  methods=['POST', 'GET'])
def admin_home():
    msg = ''
    if request.form['user'] == 'user' and request.form['pwd'] == 'user':
        return render_template("predict.html")
    else:
        msg = 'Incorrect username / password !'
    return render_template('user.html', msg=msg)



def getParameters():
    parameters = (request.form['addr'])
    print(parameters)

    return parameters

@user_bp.route('/predict',  methods=['POST', 'GET'])
def predict():
    print("hi1")
    parameters = []

    if request.method == 'POST':
        if(preprocess()=="valid"):
            print("hi2")
            parameters = getParameters()
            my_pred = data.TestModel.test_model(parameters)
            print("hi5")
            print(my_pred)
            return render_template('result.html', prediction=my_pred)
        else:
            my_pred=-1
            return render_template('result.html', prediction=my_pred)
    else:
        return render_template('predict.html')

@user_bp.route('/userlogout')
def userlogout():
    return render_template("home.html")

templates/admin.html
{% include "header.html" %}
<div class="container">
<div class="content">
                <center>
                <form action="http://localhost:5000/admin_home" method="post">

                <h1>Admin Login</h1><br>
                <ol style="list-style: none">
                    <li><input type="text" name="user" placeholder="User ID" required="" /></li><br>
                    <li><input type="password" name="pwd" placeholder="Password" required="" /></li><br>
                    <li><input type="image" name="submit" src="static/img/sub.png" class="send"/></li><br>
                </ol>
                <div class="msg">{{ msg }}</div>
                </form>
                <br><br><br><br><br><br>
                </center>
            </div>
    </div>
{% include "footer.html" %}

templates/create_model.html
{% include "header_admin.html" %}
<div class="container">

    <div style="width: 800px; height: 190px">
    <button onclick="hide_Acc()">Click here to create the model</button>
        <div class="lds-ripple" id="gear" style="display: none; margin: 150px"><div></div><div></div></div>
<div id="AccDisplay" style="display: none; width:800px; height:170px">
    <p style="color: green;font-size: large">{{ msg }}</p><br><br>
    <p style="color: maroon;font-size: large">Accuracy of the model is : {{ acc }}%</p>
</div>
</div>
</div>
{% include "footer.html" %}
	</div>
</body>
</html>

<script>
var myVar;

function hide_Acc() {
  document.getElementById("AccDisplay").style.display = "none";
  document.getElementById("gear").style.display = "block";
  myVar = setTimeout(show_Acc, 3000);
}
function show_Acc() {
document.getElementById("gear").style.display = "none";
document.getElementById("AccDisplay").style.display = "block";
}

</script>

templates/footer.html
<div class="inline-container">
    <div class="text">
    <h2></h2> <h1>Copyright@ </h1>
    </div>

</div>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flight Delay Prediction</title>
    <link  href="static/css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
<div class="wrap">
    <div class="header"><h1>Predicting Flight Delays via Large-Scale Aviation Data Processing Models</h1></div>
		<nav class="nav">
            <ul>
                <li><a href="{{ url_for('home') }}"><span>HOME</span></a></li>
                <li><a href="{{ url_for('admin_bp.admin') }}">ADMIN</a></li>
                <li><a href="{{ url_for('user_bp.user') }}">USER</a></li>
            </ul>
        </nav>

templates/header_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flight Delay Prediction</title>
    <link  href="static/css/style.css" rel="stylesheet" type="text/css">

        <style>
        .lds-ripple {
  display: inline-block;
  position: relative;
  width: 80px;
  height: 80px;
}
.lds-ripple div {
  position: absolute;
  border: 4px solid #333;
  opacity: 1;
  border-radius: 50%;
  animation: lds-ripple 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.lds-ripple div:nth-child(2) {
  animation-delay: -0.5s;
}
@keyframes lds-ripple {
  0% {
    top: 36px;
    left: 36px;
    width: 0;
    height: 0;
    opacity: 0;
  }
  4.9% {
    top: 36px;
    left: 36px;
    width: 0;
    height: 0;
    opacity: 0;
  }
  5% {
    top: 36px;
    left: 36px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 0px;
    left: 0px;
    width: 72px;
    height: 72px;
    opacity: 0;
  }
}

</style>

</head>
<body>
<div class="wrap">
    <div class="header"><h1>Predicting Flight Delays via Large-Scale Aviation Data Processing Models</h1></div>
		<nav class="nav">
            <ul>
                <li><a href="{{ url_for('admin_bp.admin_upload') }}"><span>Upload Dataset</span></a></li>
                <li><a href={{ url_for('admin_bp.cr_model') }}>Create Model</a></li>
                <li><a href={{ url_for('admin_bp.logout') }}>Logout</a></li>
            </ul>
        </nav>

templates/header_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flight Delay Prediction</title>
    <link  href="static/css/style.css" rel="stylesheet" type="text/css">

        <style>
        .lds-ripple {
  display: inline-block;
  position: relative;
  width: 80px;
  height: 80px;
}
.lds-ripple div {
  position: absolute;
  border: 4px solid #333;
  opacity: 1;
  border-radius: 50%;
  animation: lds-ripple 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.lds-ripple div:nth-child(2) {
  animation-delay: -0.5s;
}
@keyframes lds-ripple {
  0% {
    top: 36px;
    left: 36px;
    width: 0;
    height: 0;
    opacity: 0;
  }
  4.9% {
    top: 36px;
    left: 36px;
    width: 0;
    height: 0;
    opacity: 0;
  }
  5% {
    top: 36px;
    left: 36px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 0px;
    left: 0px;
    width: 72px;
    height: 72px;
    opacity: 0;
  }
}

</style>

</head>
<body>
<div class="wrap">
    <div class="header"><h1>Predicting Flight Delays via Large-Scale Aviation Data Processing Models</h1></div>
		<nav class="nav">
            <ul>
                <li><a href="{{ url_for('user_bp.predict') }}"><span>Predict</span></a></li>
                <li><a href={{ url_for('user_bp.userlogout') }}>Logout</a></li>
            </ul>
        </nav>

templates/home.html
{% include "header.html" %}
		<div class="container">
		<!--	<div class="left"></div>
			<div class="right"></div>
			<div class="clear"></div>-->
            <div class="content"><br><h1>Abstract</h1><br><br>
                <p>Delay is one of the most remembered performance indicators of any transportation system. Notably, commercial aviation players understand delay as the period by which a flight is late or postponed. Thus, a delay may be represented by the difference between scheduled and real times of departure or arrival of a plane. Country regulator authorities have a multitude of indicators related to tolerance thresholds for flight delays. Indeed, flight delay is an essential subject in the context of air transportation systems. In 2013, 36% of flights delayed by more than five minutes in Europe, 31.1% of flights delayed by more than 15 minutes in the United States. This indicates how relevant this indicator is and how it affects no matter the scale of airline meshes. To better understand the entire flight ecosystems, vast volumes of data from commercial aviation is collected every moment and stored in databases. Submerged in this massive amount of data produced by sensors and IoT, analysts and data scientists are intensifying their computational and data management skills to extract useful information from each datum. In this context, the procedure of comprehending the domain, managing data and applying a model is known as Data Science, a trend in solving challenging problems related to Big Data. In this project, we’ve performed an extensive data analysis in order to extract the important attributes/factors that are responsible for the delay of flight. Also, there will other factors that may influence the delay of the flight such as climate, natural calamities, pandemic, or technical issues, etc. in the airplane which has not been considered in this project as this factors varying depend on the location and such problems occurring have very less frequency.</p>
		</div>

	</div>
{% include "footer.html" %}
</body>
</html>

templates/predict.html
{% include "header_user.html" %}

<div class="content">


<form action="{{ url_for('user_bp.predict')}}" method="POST">
           <table>
        <tr>
            <td><label for="addr">Parameters:</label></td>
            <td><input type="text" id="addr" name="addr" placeholder="Parameters"></td>
        </tr>

        <tr>
            <td colspan="2"><input type="submit" value="Predict"></td>
        </tr>
    </table>
    </form>
</div>
{% include "footer.html" %}

templates/result.html
{% include "header_user.html" %}
<div class="content">

    {% if prediction == 0%}
	<h2 style="color:green;">This flight might be on time</h2>
	{% elif prediction == 1%}
	<h2 style="color:red;">This flight might be delayed</h2>
    {% else %}
        <h2 style="color:red;">Prediction could not be generated. Please re-load the dataset</h2>
	{% endif %}

</div>
{% include "footer.html" %}

templates/upload_dataset.html
{% include "header_admin.html" %}
<div class="content">

     <form action = "http://localhost:5000/admin_upload" method = "post" enctype="multipart/form-data">
        <br><br>
         Upload Training data file: <input type="file" name="file" /><br><br><br>
        <input type="image" name="submit" src="static/img/up.png" class="send"/><br><br>
         <div class="msg">{{ msg }}</div>
    </form>

</div>
{% include "footer.html" %}

templates/user.html
{% include "header.html" %}
<div class="content">
                <center>
                <form action="http://localhost:5000/user_home" method="post">

                <h1>User Login</h1><br>
                <ol style="list-style: none">
                    <li><input type="text" name="user" placeholder="User ID" required="" /></li><br>
                    <li><input type="password" name="pwd" placeholder="Password" required="" /></li><br>
                    <li><input type="image" name="submit" src="static/img/sub.png" class="send"/></li><br>
                </ol>
                <div class="msg">{{ msg }}</div>
                </form>
                <br><br><br><br><br><br>
                </center>
            </div>
{% include "footer.html" %}